# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-11 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_eticket_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ayat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_to_quran', models.IntegerField()),
                ('index_to_surah', models.IntegerField()),
                ('kazakh', models.CharField(max_length=700)),
                ('russian', models.CharField(max_length=700)),
                ('eng', models.CharField(max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='Sura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('arabic_name', models.CharField(max_length=30)),
                ('kazakh_name', models.CharField(max_length=39)),
                ('ayat_count', models.IntegerField()),
                ('ayat_start_index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_to_quran', models.IntegerField()),
                ('index_to_ayat', models.IntegerField()),
                ('arab', models.CharField(max_length=30)),
                ('qazaq', models.CharField(max_length=70)),
                ('qazaq_comment', models.CharField(max_length=70)),
                ('rus', models.CharField(max_length=70)),
                ('ayat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Ayat')),
            ],
        ),
        migrations.DeleteModel(
            name='Eticket',
        ),
        migrations.AddField(
            model_name='ayat',
            name='sura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Sura'),
        ),
    ]
