# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-11 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20161111_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayat',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sura',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
