# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-11 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20161111_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayat',
            name='arab',
            field=models.CharField(default='', max_length=700),
            preserve_default=False,
        ),
    ]
