# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-12 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_ayat_arab'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayat',
            name='trans',
            field=models.CharField(default='', max_length=700),
            preserve_default=False,
        ),
    ]
