# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-17 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_ayat_trans'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='eng',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
    ]
